name: CustomCompassTracker
version: 1.1.0
main: io.mewb.customcompasstracker.CustomCompassTracker
api-version: 1.16
author: Mewb
website: https://github.com/Mewb/CustomCompassTracker

description: Allows players to set and track custom locations with their compass.

commands:
  settarget:
    description: Saves your current location as a named target.
    usage: "/settarget <name>"
    permission: customcompass.use
  listtargets:
    description: Lists all your saved targets.
    usage: "/listtargets"
    permission: customcompass.use
  tracktarget:
    description: Sets your compass to track a saved target.
    usage: "/tracktarget <name>"
    permission: customcompass.use
  removetarget:
    description: Removes a saved target.
    usage: "/removetarget <name>"
    permission: customcompass.use
permissions:
  customcompass.use:
    description: Allows a player to use all features of the CustomCompassTracker plugin.
    default: true
